<?php
$xa_phuong_thitran = array(
    "0"=>array("xaid"=>"1","name"=>"Phường Hiệp Bình","tinhthanhpho"=>"HOCHIMINH"),
    "1"=>array("xaid"=>"2","name"=>"Phường Tam Bình","tinhthanhpho"=>"HOCHIMINH"),
    "2"=>array("xaid"=>"3","name"=>"Phường Thủ Đức","tinhthanhpho"=>"HOCHIMINH"),
    "3"=>array("xaid"=>"4","name"=>"Phường Linh Xuân","tinhthanhpho"=>"HOCHIMINH"),
    "4"=>array("xaid"=>"5","name"=>"Phường Long Bình","tinhthanhpho"=>"HOCHIMINH"),
    "5"=>array("xaid"=>"6","name"=>"Phường Tăng Nhơn Phú","tinhthanhpho"=>"HOCHIMINH"),
    "6"=>array("xaid"=>"7","name"=>"Phường Phước Long","tinhthanhpho"=>"HOCHIMINH"),
    "7"=>array("xaid"=>"8","name"=>"Phường Long Phước","tinhthanhpho"=>"HOCHIMINH"),
    "8"=>array("xaid"=>"9","name"=>"Phường Long Trường","tinhthanhpho"=>"HOCHIMINH"),
    "9"=>array("xaid"=>"10","name"=>"Phường An Khánh","tinhthanhpho"=>"HOCHIMINH"),
    "10"=>array("xaid"=>"11","name"=>"Phường Bình Trung","tinhthanhpho"=>"HOCHIMINH"),
    "11"=>array("xaid"=>"12","name"=>"Phường Cát Lái","tinhthanhpho"=>"HOCHIMINH"),
    "12"=>array("xaid"=>"13","name"=>"Phường Tân Định","tinhthanhpho"=>"HOCHIMINH"),
    "13"=>array("xaid"=>"14","name"=>"Phường Bến Thành","tinhthanhpho"=>"HOCHIMINH"),
    "14"=>array("xaid"=>"15","name"=>"Phường Sài Gòn","tinhthanhpho"=>"HOCHIMINH"),
    "15"=>array("xaid"=>"16","name"=>"Phường Cầu Ông Lãnh","tinhthanhpho"=>"HOCHIMINH"),
    "16"=>array("xaid"=>"17","name"=>"Phường Bàn Cờ","tinhthanhpho"=>"HOCHIMINH"),
    "17"=>array("xaid"=>"18","name"=>"Phường Xuân Hòa","tinhthanhpho"=>"HOCHIMINH"),
    "18"=>array("xaid"=>"19","name"=>"Phường Nhiêu Lộc","tinhthanhpho"=>"HOCHIMINH"),
    "19"=>array("xaid"=>"20","name"=>"Phường Vĩnh Hội","tinhthanhpho"=>"HOCHIMINH"),
    "20"=>array("xaid"=>"21","name"=>"Phường Khánh Hội","tinhthanhpho"=>"HOCHIMINH"),
    "21"=>array("xaid"=>"22","name"=>"Phường Xóm Chiếu","tinhthanhpho"=>"HOCHIMINH"),
    "22"=>array("xaid"=>"23","name"=>"Phường Chợ Quán","tinhthanhpho"=>"HOCHIMINH"),
    "23"=>array("xaid"=>"24","name"=>"Phường An Đông","tinhthanhpho"=>"HOCHIMINH"),
    "24"=>array("xaid"=>"25","name"=>"Phường Chợ Lớn","tinhthanhpho"=>"HOCHIMINH"),
    "25"=>array("xaid"=>"26","name"=>"Phường Bình Tiên","tinhthanhpho"=>"HOCHIMINH"),
    "26"=>array("xaid"=>"27","name"=>"Phường Bình Tây","tinhthanhpho"=>"HOCHIMINH"),
    "27"=>array("xaid"=>"28","name"=>"Phường Bình Phú","tinhthanhpho"=>"HOCHIMINH"),
    "28"=>array("xaid"=>"29","name"=>"Phường Phú Lâm","tinhthanhpho"=>"HOCHIMINH"),
    "29"=>array("xaid"=>"30","name"=>"Phường Tân Mỹ","tinhthanhpho"=>"HOCHIMINH"),
    "30"=>array("xaid"=>"31","name"=>"Phường Tân Hưng","tinhthanhpho"=>"HOCHIMINH"),
    "31"=>array("xaid"=>"32","name"=>"Phường Tân Thuận","tinhthanhpho"=>"HOCHIMINH"),
    "32"=>array("xaid"=>"33","name"=>"Phường Phú Thuận","tinhthanhpho"=>"HOCHIMINH"),
    "33"=>array("xaid"=>"34","name"=>"Phường Chánh Hưng","tinhthanhpho"=>"HOCHIMINH"),
    "34"=>array("xaid"=>"35","name"=>"Phường Bình Đông","tinhthanhpho"=>"HOCHIMINH"),
    "35"=>array("xaid"=>"36","name"=>"Phường Phú Định","tinhthanhpho"=>"HOCHIMINH"),
    "36"=>array("xaid"=>"37","name"=>"Phường Vườn Lài","tinhthanhpho"=>"HOCHIMINH"),
    "37"=>array("xaid"=>"38","name"=>"Phường Diên Hồng","tinhthanhpho"=>"HOCHIMINH"),
    "38"=>array("xaid"=>"39","name"=>"Phường Hòa Hưng","tinhthanhpho"=>"HOCHIMINH"),
    "39"=>array("xaid"=>"40","name"=>"Phường Hòa Bình","tinhthanhpho"=>"HOCHIMINH"),
    "40"=>array("xaid"=>"41","name"=>"Phường Phú Thọ","tinhthanhpho"=>"HOCHIMINH"),
    "41"=>array("xaid"=>"42","name"=>"Phường Bình Thới","tinhthanhpho"=>"HOCHIMINH"),
    "42"=>array("xaid"=>"43","name"=>"Phường Minh Phụng","tinhthanhpho"=>"HOCHIMINH"),
    "43"=>array("xaid"=>"44","name"=>"Phường Đông Hưng Thuận","tinhthanhpho"=>"HOCHIMINH"),
    "44"=>array("xaid"=>"45","name"=>"Phường Trung Mỹ Tây","tinhthanhpho"=>"HOCHIMINH"),
    "45"=>array("xaid"=>"46","name"=>"Phường Tân Thới Hiệp","tinhthanhpho"=>"HOCHIMINH"),
    "46"=>array("xaid"=>"47","name"=>"Phường Thới An","tinhthanhpho"=>"HOCHIMINH"),
    "47"=>array("xaid"=>"48","name"=>"Phường An Phú Đông","tinhthanhpho"=>"HOCHIMINH"),
    "48"=>array("xaid"=>"49","name"=>"Phường Gia Định","tinhthanhpho"=>"HOCHIMINH"),
    "49"=>array("xaid"=>"50","name"=>"Phường Bình Thạnh","tinhthanhpho"=>"HOCHIMINH"),
    "50"=>array("xaid"=>"51","name"=>"Phường Bình Lợi Trung","tinhthanhpho"=>"HOCHIMINH"),
    "51"=>array("xaid"=>"52","name"=>"Phường Thạnh Mỹ Tây","tinhthanhpho"=>"HOCHIMINH"),
    "52"=>array("xaid"=>"53","name"=>"Phường Bình Quới","tinhthanhpho"=>"HOCHIMINH"),
    "53"=>array("xaid"=>"54","name"=>"Phường Bình Tân","tinhthanhpho"=>"HOCHIMINH"),
    "54"=>array("xaid"=>"55","name"=>"Phường Bình Hưng Hòa","tinhthanhpho"=>"HOCHIMINH"),
    "55"=>array("xaid"=>"56","name"=>"Phường Bình Trị Đông","tinhthanhpho"=>"HOCHIMINH"),
    "56"=>array("xaid"=>"57","name"=>"Phường An Lạc","tinhthanhpho"=>"HOCHIMINH"),
    "57"=>array("xaid"=>"58","name"=>"Phường Tân Tạo","tinhthanhpho"=>"HOCHIMINH"),
    "58"=>array("xaid"=>"59","name"=>"Phường Hạnh Thông","tinhthanhpho"=>"HOCHIMINH"),
    "59"=>array("xaid"=>"60","name"=>"Phường An Nhơn","tinhthanhpho"=>"HOCHIMINH"),
    "60"=>array("xaid"=>"61","name"=>"Phường Gò Vấp","tinhthanhpho"=>"HOCHIMINH"),
    "61"=>array("xaid"=>"62","name"=>"Phường Thông Tây Hội","tinhthanhpho"=>"HOCHIMINH"),
    "62"=>array("xaid"=>"63","name"=>"Phường An Hội Tây","tinhthanhpho"=>"HOCHIMINH"),
    "63"=>array("xaid"=>"64","name"=>"Phường An Hội Đông","tinhthanhpho"=>"HOCHIMINH"),
    "64"=>array("xaid"=>"65","name"=>"Phường Đức Nhuận","tinhthanhpho"=>"HOCHIMINH"),
    "65"=>array("xaid"=>"66","name"=>"Phường Cầu Kiệu","tinhthanhpho"=>"HOCHIMINH"),
    "66"=>array("xaid"=>"67","name"=>"Phường Phú Nhuận","tinhthanhpho"=>"HOCHIMINH"),
    "67"=>array("xaid"=>"68","name"=>"Phường Tân Sơn Hòa","tinhthanhpho"=>"HOCHIMINH"),
    "68"=>array("xaid"=>"69","name"=>"Phường Tân Sơn Nhất","tinhthanhpho"=>"HOCHIMINH"),
    "69"=>array("xaid"=>"70","name"=>"Phường Tân Hòa","tinhthanhpho"=>"HOCHIMINH"),
    "70"=>array("xaid"=>"71","name"=>"Phường Bảy Hiền","tinhthanhpho"=>"HOCHIMINH"),
    "71"=>array("xaid"=>"72","name"=>"Phường Tân Bình","tinhthanhpho"=>"HOCHIMINH"),
    "72"=>array("xaid"=>"73","name"=>"Phường Tân Sơn","tinhthanhpho"=>"HOCHIMINH"),
    "73"=>array("xaid"=>"74","name"=>"Phường Tây Thạnh","tinhthanhpho"=>"HOCHIMINH"),
    "74"=>array("xaid"=>"75","name"=>"Phường Tân Sơn Nhì","tinhthanhpho"=>"HOCHIMINH"),
    "75"=>array("xaid"=>"76","name"=>"Phường Phú Thọ Hòa","tinhthanhpho"=>"HOCHIMINH"),
    "76"=>array("xaid"=>"77","name"=>"Phường Phú Thạnh","tinhthanhpho"=>"HOCHIMINH"),
    "77"=>array("xaid"=>"78","name"=>"Phường Tân Phú","tinhthanhpho"=>"HOCHIMINH"),
    "78"=>array("xaid"=>"79","name"=>"Xã Vĩnh Lộc","tinhthanhpho"=>"HOCHIMINH"),
    "79"=>array("xaid"=>"80","name"=>"Xã Tân Vĩnh Lộc","tinhthanhpho"=>"HOCHIMINH"),
    "80"=>array("xaid"=>"81","name"=>"Xã Bình Lợi","tinhthanhpho"=>"HOCHIMINH"),
    "81"=>array("xaid"=>"82","name"=>"Xã Tân Nhựt","tinhthanhpho"=>"HOCHIMINH"),
    "82"=>array("xaid"=>"83","name"=>"Xã Bình Chánh","tinhthanhpho"=>"HOCHIMINH"),
    "83"=>array("xaid"=>"84","name"=>"Xã Hưng Long","tinhthanhpho"=>"HOCHIMINH"),
    "84"=>array("xaid"=>"85","name"=>"Xã Bình Hưng","tinhthanhpho"=>"HOCHIMINH"),
    "85"=>array("xaid"=>"86","name"=>"Xã An Nhơn Tây","tinhthanhpho"=>"HOCHIMINH"),
    "86"=>array("xaid"=>"87","name"=>"Xã Thái Mỹ","tinhthanhpho"=>"HOCHIMINH"),
    "87"=>array("xaid"=>"88","name"=>"Xã Nhuận Đức","tinhthanhpho"=>"HOCHIMINH"),
    "88"=>array("xaid"=>"89","name"=>"Xã Tân An Hội","tinhthanhpho"=>"HOCHIMINH"),
    "89"=>array("xaid"=>"90","name"=>"Xã Củ Chi","tinhthanhpho"=>"HOCHIMINH"),
    "90"=>array("xaid"=>"91","name"=>"Xã Phú Hòa Đông","tinhthanhpho"=>"HOCHIMINH"),
    "91"=>array("xaid"=>"92","name"=>"Xã Bình Mỹ","tinhthanhpho"=>"HOCHIMINH"),
    "92"=>array("xaid"=>"93","name"=>"Xã Bình Khánh","tinhthanhpho"=>"HOCHIMINH"),
    "93"=>array("xaid"=>"94","name"=>"Xã Cần Giờ","tinhthanhpho"=>"HOCHIMINH"),
    "94"=>array("xaid"=>"95","name"=>"Xã An Thới Đông","tinhthanhpho"=>"HOCHIMINH"),
    "95"=>array("xaid"=>"96","name"=>"Xã Thạnh An","tinhthanhpho"=>"HOCHIMINH"),
    "96"=>array("xaid"=>"97","name"=>"Xã Hóc Môn","tinhthanhpho"=>"HOCHIMINH"),
    "97"=>array("xaid"=>"98","name"=>"Xã Bà Điểm","tinhthanhpho"=>"HOCHIMINH"),
    "98"=>array("xaid"=>"99","name"=>"Xã Xuân Thới Sơn","tinhthanhpho"=>"HOCHIMINH"),
    "99"=>array("xaid"=>"100","name"=>"Xã Đông Thạnh","tinhthanhpho"=>"HOCHIMINH"),
    "100"=>array("xaid"=>"101","name"=>"Xã Nhà Bè","tinhthanhpho"=>"HOCHIMINH"),
    "101"=>array("xaid"=>"102","name"=>"Xã Hiệp Phước","tinhthanhpho"=>"HOCHIMINH")
);
